services:
  database:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: feature-flag
      POSTGRES_USER: feature-flag
      POSTGRES_PASSWORD: feature-flag
    ports:
      - 5432:5432

  application:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  pgdata:
