apiVersion: v1
kind: Namespace
metadata:
  name: feature-flag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag
  namespace: feature-flag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-flag
  template:
    metadata:
      labels:
        app: feature-flag
    spec:
      containers:
        - name: feature-flag
          image: demo-api-d44df51:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flag
  namespace: feature-flag
spec:
  type: NodePort
  selector:
    app: feature-flag
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
